spring:
  profiles:
    active: "dev"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      default_schema: public
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    show-sql: false
  liquibase:
    enabled: true
  mvc:
    async:
      request-timeout: 600000
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /api-docs
  enable-native-support: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    path: /swagger-ui
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gcp:
      sql:
        enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/demohackaton?searchpath=public&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok&prepareThreshold=0
    username: root
    password: 12345678
    hikari:
      schema: public
      connectionTimeout: 30000
      leakDetectionThreshold: 120000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: postgres
    password: cr3ateder!
    url: jdbc:postgresql://office.createder.com:5432/txventure?searchpath=public&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok&prepareThreshold=0
---