version: '3'
name: sgh2023
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    command: celery -A main worker --loglevel=info
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    command: celery -A main beat --loglevel=info
  flower:
    image: mher/flower
    ports:
      - '5555:5555'
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - FLOWER_PORT=5555
    depends_on:
      - redis
      - worker
    restart: always
    command: celery flower -A main --loglevel=info

